architecture: "hybrid_segformer_umamba"
params:
  in_channels: 3
  out_channels: 1
  spatial_dims: 3
  deep_supervision: true
  fusion_dim: 96
  bridge_dim: 96
  embed_dims: [64, 128, 320, 512]
  decoder_dims: [256, 128, 64]